### ISSUE TITLE
Can't go backwards or select image

### ISSUE THREAD

**Issue by JuanPotato** [asarode/seen-it#10]
When I want to choose an image from the sidebar or go backwards using the button, it just goes to the next post. If I have time I'll look through the code and see if I can fix it, though I'm procrastinating right now doing an essay that is due tomorrow. Great extension :+1: .

**Comment by asarode** [comment]
Right now you can click the icon in the bar and disable skipping in the options. I think adding in #2 should count as fixing this issue.

**Comment by asarode** [comment]
Just pulled #7 which lets you press alt+z to toggle the skip option and alt+x to toggle the storing option. We should get another issue going for enabling people to have the option to select which hotkey they want.
