### ISSUE TITLE
extend url matching to https

### ISSUE THREAD

**Issue by LaxisB** [asarode/seen-it#5]
http(s)?:\/\/imgur.com

see `function checkForImgurUrl(tabId, changeInfo, tab) {
  if (changeInfo.status === 'complete') {
    if (tab.url.indexOf('http://imgur.com') === 0) {
      chrome.pageAction.show(tabId);
      processUrl(tab.url);
    } else {
      chrome.pageAction.hide(tabId);
    }
  }
}
`

this can be fixed if the check is made using this regex
/http(s)?:\/\/imgur.com/i

**Comment by asarode** [comment]
Good catch! This should be fixed along with #1 
I won't be able to take care of this until Tuesday or Wednesday night though. Feel free to fork the repo, commit the changes, and submit a pull request.

**Comment by asarode** [comment]
Pull request #8 made the url check for "://imgur.com" instead of needing to check for http or https. That should fix this issue.
